2018-09-01 12:57:04,261 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-01 12:57:04,261 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-01 12:57:04,301 [open_context_base.py] _handle_init_connect:366: sync socket init_connect ok: {'server_version': 102, 'login_user_id': 11326113, 'conn_id': 13765347378388801221, 'conn_key': 'C616B83A8257083C', 'keep_alive_interval': 10}
2018-09-01 13:24:55,505 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-01 13:24:55,506 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-01 13:24:55,566 [open_context_base.py] _handle_init_connect:366: sync socket init_connect ok: {'server_version': 102, 'login_user_id': 11326113, 'conn_id': 8793474571581730569, 'conn_key': '012F8F7488B30857', 'keep_alive_interval': 10}
2018-09-01 13:44:12,838 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-01 13:44:12,838 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-01 13:44:12,878 [open_context_base.py] _handle_init_connect:366: sync socket init_connect ok: {'server_version': 102, 'login_user_id': 11326113, 'conn_id': 5550964222252465378, 'conn_key': 'E7BC42C48CFD0802', 'keep_alive_interval': 10}
2018-09-01 17:15:12,960 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-01 17:15:12,961 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-01 17:15:13,001 [open_context_base.py] _handle_init_connect:366: sync socket init_connect ok: {'server_version': 102, 'login_user_id': 11326113, 'conn_id': 13117845228610865221, 'conn_key': '4548E7EDBBF30BAB', 'keep_alive_interval': 10}
2018-09-02 23:16:25,926 [open_context_base.py] on_closed:311: Connect closed: conn_id=1
2018-09-02 23:16:25,948 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:16:33,963 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:16:33,964 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:16:33,984 [open_context_base.py] on_error:303: Connect error: conn_id=2; err=[Errno 111] Connection refused;
2018-09-02 23:16:33,994 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:16:41,996 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:16:41,997 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:16:41,997 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:16:49,997 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:16:49,998 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:16:50,002 [open_context_base.py] on_error:303: Connect error: conn_id=4; err=[Errno 111] Connection refused;
2018-09-02 23:16:50,011 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:16:58,011 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:16:58,011 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:16:58,021 [open_context_base.py] on_error:303: Connect error: conn_id=5; err=[Errno 111] Connection refused;
2018-09-02 23:16:58,022 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:17:06,022 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:17:06,022 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:17:06,040 [open_context_base.py] on_error:303: Connect error: conn_id=6; err=[Errno 111] Connection refused;
2018-09-02 23:17:06,043 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:17:14,043 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:17:14,043 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:17:14,058 [open_context_base.py] on_error:303: Connect error: conn_id=7; err=[Errno 111] Connection refused;
2018-09-02 23:17:14,064 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:17:22,064 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:17:22,065 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:17:22,077 [open_context_base.py] on_error:303: Connect error: conn_id=8; err=[Errno 111] Connection refused;
2018-09-02 23:17:22,085 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:17:30,085 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:17:30,086 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:17:30,097 [open_context_base.py] on_error:303: Connect error: conn_id=9; err=[Errno 111] Connection refused;
2018-09-02 23:17:30,106 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:17:38,106 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:17:38,107 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:17:38,117 [open_context_base.py] on_error:303: Connect error: conn_id=10; err=[Errno 111] Connection refused;
2018-09-02 23:17:38,118 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:17:46,118 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:17:46,118 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:17:46,137 [open_context_base.py] on_error:303: Connect error: conn_id=11; err=[Errno 111] Connection refused;
2018-09-02 23:17:46,139 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:17:54,139 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:17:54,139 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:17:54,156 [open_context_base.py] on_error:303: Connect error: conn_id=12; err=[Errno 111] Connection refused;
2018-09-02 23:17:54,160 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:18:02,160 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:18:02,160 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:18:02,176 [open_context_base.py] on_error:303: Connect error: conn_id=13; err=[Errno 111] Connection refused;
2018-09-02 23:18:02,182 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:18:10,182 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:18:10,182 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:18:10,195 [open_context_base.py] on_error:303: Connect error: conn_id=14; err=[Errno 111] Connection refused;
2018-09-02 23:18:10,203 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:18:18,203 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:18:18,203 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:18:18,215 [open_context_base.py] on_error:303: Connect error: conn_id=15; err=[Errno 111] Connection refused;
2018-09-02 23:18:18,224 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:18:26,224 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:18:26,224 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:18:26,235 [open_context_base.py] on_error:303: Connect error: conn_id=16; err=[Errno 111] Connection refused;
2018-09-02 23:18:26,255 [open_context_base.py] on_closed:311: Connect closed: conn_id=16
2018-09-02 23:18:26,256 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:18:34,256 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:18:34,256 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:18:34,276 [open_context_base.py] on_error:303: Connect error: conn_id=17; err=[Errno 111] Connection refused;
2018-09-02 23:18:34,277 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:18:42,278 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:18:42,278 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:18:42,296 [open_context_base.py] on_error:303: Connect error: conn_id=18; err=[Errno 111] Connection refused;
2018-09-02 23:18:42,298 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:18:50,298 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:18:50,310 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:18:50,318 [open_context_base.py] on_error:303: Connect error: conn_id=19; err=[Errno 111] Connection refused;
2018-09-02 23:18:50,320 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:18:58,320 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:18:58,321 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:18:58,338 [open_context_base.py] on_error:303: Connect error: conn_id=20; err=[Errno 111] Connection refused;
2018-09-02 23:18:58,342 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:19:06,342 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:19:06,342 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:19:06,358 [open_context_base.py] on_error:303: Connect error: conn_id=21; err=[Errno 111] Connection refused;
2018-09-02 23:19:06,362 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:19:14,363 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:19:14,363 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:19:14,378 [open_context_base.py] on_error:303: Connect error: conn_id=22; err=[Errno 111] Connection refused;
2018-09-02 23:19:14,383 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:19:22,384 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:19:22,384 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:19:22,398 [open_context_base.py] on_error:303: Connect error: conn_id=23; err=[Errno 111] Connection refused;
2018-09-02 23:19:22,405 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:19:30,405 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:19:30,405 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:19:30,418 [open_context_base.py] on_error:303: Connect error: conn_id=24; err=[Errno 111] Connection refused;
2018-09-02 23:19:30,426 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:19:38,426 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:19:38,426 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:19:38,439 [open_context_base.py] on_error:303: Connect error: conn_id=25; err=[Errno 111] Connection refused;
2018-09-02 23:19:38,447 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:19:46,447 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:19:46,447 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:19:46,459 [open_context_base.py] on_error:303: Connect error: conn_id=26; err=[Errno 111] Connection refused;
2018-09-02 23:19:46,468 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:19:54,468 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:19:54,469 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:19:54,477 [open_context_base.py] on_error:303: Connect error: conn_id=27; err=[Errno 111] Connection refused;
2018-09-02 23:19:54,479 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:20:02,479 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:20:02,480 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:20:02,498 [open_context_base.py] on_error:303: Connect error: conn_id=28; err=[Errno 111] Connection refused;
2018-09-02 23:20:02,500 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:20:10,500 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:20:10,501 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:20:10,518 [open_context_base.py] on_error:303: Connect error: conn_id=29; err=[Errno 111] Connection refused;
2018-09-02 23:20:10,521 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:20:18,521 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:20:18,521 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:20:18,537 [open_context_base.py] on_error:303: Connect error: conn_id=30; err=[Errno 111] Connection refused;
2018-09-02 23:20:18,542 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:20:26,542 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:20:26,542 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:20:26,557 [open_context_base.py] on_error:303: Connect error: conn_id=31; err=[Errno 111] Connection refused;
2018-09-02 23:20:26,563 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:20:34,563 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:20:34,564 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:20:34,575 [open_context_base.py] on_error:303: Connect error: conn_id=32; err=[Errno 111] Connection refused;
2018-09-02 23:20:34,584 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:20:42,585 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:20:42,585 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:20:42,595 [open_context_base.py] on_error:303: Connect error: conn_id=33; err=[Errno 111] Connection refused;
2018-09-02 23:20:42,596 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:20:50,596 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:20:50,597 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:20:50,614 [open_context_base.py] on_error:303: Connect error: conn_id=34; err=[Errno 111] Connection refused;
2018-09-02 23:20:50,617 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:20:58,629 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:20:58,629 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:20:58,633 [open_context_base.py] on_error:303: Connect error: conn_id=35; err=[Errno 111] Connection refused;
2018-09-02 23:20:58,639 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:21:06,640 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:21:06,640 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:21:06,652 [open_context_base.py] on_error:303: Connect error: conn_id=36; err=[Errno 111] Connection refused;
2018-09-02 23:21:06,661 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:21:14,661 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:21:14,661 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:21:14,671 [open_context_base.py] on_error:303: Connect error: conn_id=37; err=[Errno 111] Connection refused;
2018-09-02 23:21:14,672 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:21:22,672 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:21:22,672 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:21:22,692 [open_context_base.py] on_error:303: Connect error: conn_id=38; err=[Errno 111] Connection refused;
2018-09-02 23:21:22,712 [open_context_base.py] on_closed:311: Connect closed: conn_id=38
2018-09-02 23:21:22,713 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:21:30,714 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:21:30,714 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:21:30,731 [open_context_base.py] on_error:303: Connect error: conn_id=39; err=[Errno 111] Connection refused;
2018-09-02 23:21:30,734 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:21:38,735 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:21:38,735 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:21:38,750 [open_context_base.py] on_error:303: Connect error: conn_id=40; err=[Errno 111] Connection refused;
2018-09-02 23:21:38,755 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:21:46,756 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:21:46,767 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:21:46,770 [open_context_base.py] on_error:303: Connect error: conn_id=41; err=[Errno 111] Connection refused;
2018-09-02 23:21:46,777 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:21:54,778 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:21:54,778 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:21:54,789 [open_context_base.py] on_error:303: Connect error: conn_id=42; err=[Errno 111] Connection refused;
2018-09-02 23:21:54,798 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:22:02,799 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:22:02,799 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:22:02,809 [open_context_base.py] on_error:303: Connect error: conn_id=43; err=[Errno 111] Connection refused;
2018-09-02 23:22:02,810 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:22:10,810 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:22:10,811 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:22:10,811 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:22:18,812 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:22:18,812 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:22:18,827 [open_context_base.py] on_error:303: Connect error: conn_id=45; err=[Errno 111] Connection refused;
2018-09-02 23:22:18,833 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:22:26,833 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:22:26,833 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:22:26,848 [open_context_base.py] on_error:303: Connect error: conn_id=46; err=[Errno 111] Connection refused;
2018-09-02 23:22:26,854 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:22:34,854 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:22:34,855 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:22:34,868 [open_context_base.py] on_error:303: Connect error: conn_id=47; err=[Errno 111] Connection refused;
2018-09-02 23:22:34,875 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:22:42,876 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:22:42,876 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:22:42,888 [open_context_base.py] on_error:303: Connect error: conn_id=48; err=[Errno 111] Connection refused;
2018-09-02 23:22:42,896 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:22:50,897 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:22:50,897 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:22:50,907 [open_context_base.py] on_error:303: Connect error: conn_id=49; err=[Errno 111] Connection refused;
2018-09-02 23:22:50,917 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:22:58,918 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:22:58,918 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:22:58,929 [open_context_base.py] on_error:303: Connect error: conn_id=50; err=[Errno 111] Connection refused;
2018-09-02 23:22:58,938 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:23:06,939 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:23:06,939 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:23:06,949 [open_context_base.py] on_error:303: Connect error: conn_id=51; err=[Errno 111] Connection refused;
2018-09-02 23:23:06,960 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:23:14,960 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:23:14,961 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:23:14,967 [open_context_base.py] on_error:303: Connect error: conn_id=52; err=[Errno 111] Connection refused;
2018-09-02 23:23:14,971 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:23:22,971 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:23:22,972 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:23:22,988 [open_context_base.py] on_error:303: Connect error: conn_id=53; err=[Errno 111] Connection refused;
2018-09-02 23:23:22,992 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:23:30,993 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:23:30,993 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:23:31,007 [open_context_base.py] on_error:303: Connect error: conn_id=54; err=[Errno 111] Connection refused;
2018-09-02 23:23:31,013 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:23:39,014 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:23:39,014 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:23:39,028 [open_context_base.py] on_error:303: Connect error: conn_id=55; err=[Errno 111] Connection refused;
2018-09-02 23:23:39,034 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:23:47,035 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:23:47,035 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:23:47,048 [open_context_base.py] on_error:303: Connect error: conn_id=56; err=[Errno 111] Connection refused;
2018-09-02 23:23:47,056 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:23:55,056 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:23:55,056 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:23:55,067 [open_context_base.py] on_error:303: Connect error: conn_id=57; err=[Errno 111] Connection refused;
2018-09-02 23:23:55,077 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:24:03,077 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:24:03,078 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:24:03,085 [open_context_base.py] on_error:303: Connect error: conn_id=58; err=[Errno 111] Connection refused;
2018-09-02 23:24:03,088 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:24:11,088 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:24:11,088 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:24:11,104 [open_context_base.py] on_error:303: Connect error: conn_id=59; err=[Errno 111] Connection refused;
2018-09-02 23:24:11,109 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:24:19,109 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:24:19,110 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:24:19,123 [open_context_base.py] on_error:303: Connect error: conn_id=60; err=[Errno 111] Connection refused;
2018-09-02 23:24:19,131 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:24:27,131 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:24:27,131 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:24:27,144 [open_context_base.py] on_error:303: Connect error: conn_id=61; err=[Errno 111] Connection refused;
2018-09-02 23:24:27,152 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:24:35,152 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:24:35,152 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:24:35,165 [open_context_base.py] on_error:303: Connect error: conn_id=62; err=[Errno 111] Connection refused;
2018-09-02 23:24:35,173 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:24:43,173 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:24:43,173 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:24:43,185 [open_context_base.py] on_error:303: Connect error: conn_id=63; err=[Errno 111] Connection refused;
2018-09-02 23:24:43,194 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:24:51,195 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:24:51,195 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:24:51,205 [open_context_base.py] on_error:303: Connect error: conn_id=64; err=[Errno 111] Connection refused;
2018-09-02 23:24:51,205 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:24:59,206 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:24:59,206 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:24:59,225 [open_context_base.py] on_error:303: Connect error: conn_id=65; err=[Errno 111] Connection refused;
2018-09-02 23:24:59,227 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:25:07,227 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:25:07,227 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:25:07,246 [open_context_base.py] on_error:303: Connect error: conn_id=66; err=[Errno 111] Connection refused;
2018-09-02 23:25:07,248 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:25:15,249 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:25:15,249 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:25:15,266 [open_context_base.py] on_error:303: Connect error: conn_id=67; err=[Errno 111] Connection refused;
2018-09-02 23:25:15,269 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:25:23,270 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:25:23,270 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:25:23,287 [open_context_base.py] on_error:303: Connect error: conn_id=68; err=[Errno 111] Connection refused;
2018-09-02 23:25:23,290 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:25:31,291 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:25:31,291 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:25:31,308 [open_context_base.py] on_error:303: Connect error: conn_id=69; err=[Errno 111] Connection refused;
2018-09-02 23:25:31,312 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:25:39,312 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:25:39,312 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:25:39,328 [open_context_base.py] on_error:303: Connect error: conn_id=70; err=[Errno 111] Connection refused;
2018-09-02 23:25:39,333 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:25:47,333 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:25:47,333 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:25:47,348 [open_context_base.py] on_error:303: Connect error: conn_id=71; err=[Errno 111] Connection refused;
2018-09-02 23:25:47,354 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:25:55,354 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:25:55,354 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:25:55,367 [open_context_base.py] on_error:303: Connect error: conn_id=72; err=[Errno 111] Connection refused;
2018-09-02 23:25:55,375 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:26:03,376 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:26:03,376 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:26:03,387 [open_context_base.py] on_error:303: Connect error: conn_id=73; err=[Errno 111] Connection refused;
2018-09-02 23:26:03,396 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:26:11,397 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:26:11,397 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:26:11,406 [open_context_base.py] on_error:303: Connect error: conn_id=74; err=[Errno 111] Connection refused;
2018-09-02 23:26:11,407 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:26:19,408 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:26:19,408 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:26:19,426 [open_context_base.py] on_error:303: Connect error: conn_id=75; err=[Errno 111] Connection refused;
2018-09-02 23:26:19,429 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:26:27,429 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:26:27,429 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:26:27,446 [open_context_base.py] on_error:303: Connect error: conn_id=76; err=[Errno 111] Connection refused;
2018-09-02 23:26:27,450 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:26:35,450 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:26:35,450 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:26:35,466 [open_context_base.py] on_error:303: Connect error: conn_id=77; err=[Errno 111] Connection refused;
2018-09-02 23:26:35,471 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:26:43,471 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:26:43,471 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:26:43,485 [open_context_base.py] on_error:303: Connect error: conn_id=78; err=[Errno 111] Connection refused;
2018-09-02 23:26:43,492 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:26:51,492 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:26:51,493 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:26:51,504 [open_context_base.py] on_error:303: Connect error: conn_id=79; err=[Errno 111] Connection refused;
2018-09-02 23:26:51,513 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:26:59,514 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:26:59,514 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:26:59,524 [open_context_base.py] on_error:303: Connect error: conn_id=80; err=[Errno 111] Connection refused;
2018-09-02 23:26:59,525 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:27:07,525 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:27:07,526 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:27:07,544 [open_context_base.py] on_error:303: Connect error: conn_id=81; err=[Errno 111] Connection refused;
2018-09-02 23:27:07,546 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:27:15,547 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:27:15,547 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:27:15,563 [open_context_base.py] on_error:303: Connect error: conn_id=82; err=[Errno 111] Connection refused;
2018-09-02 23:27:15,568 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:27:23,568 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:27:23,568 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:27:23,582 [open_context_base.py] on_error:303: Connect error: conn_id=83; err=[Errno 111] Connection refused;
2018-09-02 23:27:23,589 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:27:31,590 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:27:31,590 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:27:31,601 [open_context_base.py] on_error:303: Connect error: conn_id=84; err=[Errno 111] Connection refused;
2018-09-02 23:27:31,610 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:27:39,611 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:27:39,611 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:27:39,622 [open_context_base.py] on_error:303: Connect error: conn_id=85; err=[Errno 111] Connection refused;
2018-09-02 23:27:39,632 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:27:47,632 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:27:47,632 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:27:47,642 [open_context_base.py] on_error:303: Connect error: conn_id=86; err=[Errno 111] Connection refused;
2018-09-02 23:27:47,643 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:27:55,644 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:27:55,644 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:27:55,661 [open_context_base.py] on_error:303: Connect error: conn_id=87; err=[Errno 111] Connection refused;
2018-09-02 23:27:55,665 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:28:03,665 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:28:03,665 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:28:03,682 [open_context_base.py] on_error:303: Connect error: conn_id=88; err=[Errno 111] Connection refused;
2018-09-02 23:28:03,686 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:28:11,686 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:28:11,686 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:28:11,703 [open_context_base.py] on_error:303: Connect error: conn_id=89; err=[Errno 111] Connection refused;
2018-09-02 23:28:11,707 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:28:19,707 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:28:19,707 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:28:19,723 [open_context_base.py] on_error:303: Connect error: conn_id=90; err=[Errno 111] Connection refused;
2018-09-02 23:28:19,728 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:28:27,729 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:28:27,729 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:28:27,743 [open_context_base.py] on_error:303: Connect error: conn_id=91; err=[Errno 111] Connection refused;
2018-09-02 23:28:27,749 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:28:35,750 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:28:35,750 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:28:35,763 [open_context_base.py] on_error:303: Connect error: conn_id=92; err=[Errno 111] Connection refused;
2018-09-02 23:28:35,771 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:28:43,771 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:28:43,771 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:28:43,784 [open_context_base.py] on_error:303: Connect error: conn_id=93; err=[Errno 111] Connection refused;
2018-09-02 23:28:43,792 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:28:51,793 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:28:51,793 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:28:51,803 [open_context_base.py] on_error:303: Connect error: conn_id=94; err=[Errno 111] Connection refused;
2018-09-02 23:28:51,813 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:28:59,825 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:28:59,825 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:28:59,845 [open_context_base.py] on_error:303: Connect error: conn_id=95; err=[Errno 111] Connection refused;
2018-09-02 23:28:59,846 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:29:07,847 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:29:07,847 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:29:07,866 [open_context_base.py] on_error:303: Connect error: conn_id=96; err=[Errno 111] Connection refused;
2018-09-02 23:29:07,867 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:29:15,868 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:29:15,868 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:29:15,884 [open_context_base.py] on_error:303: Connect error: conn_id=97; err=[Errno 111] Connection refused;
2018-09-02 23:29:15,889 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2018-09-02 23:29:23,889 [open_context_base.py] _socket_reconnect_and_wait_ready:205: Start connecting: host=127.0.0.1; port=11111;
2018-09-02 23:29:23,890 [open_context_base.py] _socket_reconnect_and_wait_ready:208: try connecting: host=127.0.0.1; port=11111;
2018-09-02 23:29:23,904 [open_context_base.py] on_error:303: Connect error: conn_id=98; err=[Errno 111] Connection refused;
2018-09-02 23:29:23,910 [open_context_base.py] _wait_reconnect:379: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
